apiVersion: batch/v1
kind: Job
metadata:
  name: wasmdemo
spec:
  template:
    spec:
      runtimeClassName: wasm
      containers:
        - image: ghcr.io/adevjoe/wasmdemo:1.3
          imagePullPolicy: Always
          name: wasmdemo
      restartPolicy: Never
  backoffLimit: 1
