apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasm
handler: wasm
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wasmdemo
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat
    spec:
      runtimeClassName: wasm
      containers:
        - image: ghcr.io/adevjoe/wasmdemo:1.0
          name: wasmdemo
      restartPolicy: Never
  backoffLimit: 1
